### ISSUE TITLE
docs need updating

### ISSUE THREAD

**Issue by Maxhodges** [Konecty/meteor-mongo-counter#2]
Hi, thanks for turning on Issues.

We have trouble with this package for a while because the function sig changed, but the readme doesn't reflect the change yet. Did you see there is a pull request for the doc fix?

Cheers!

**Comment by osv** [comment]
+1
I think those who use original pkg before, may be confused :)

**Comment by theduke** [comment]
+1

**Comment by Maxhodges** [comment]
could you give permission to me or another use to maintain pull requests if you are too busy or no longer interested to maintain this package? 
Cheers!

**Comment by sampaiodiego** [comment]
hey @Maxhodges, thanks for the concern. The docs are already updated via pull request.
