### ISSUE TITLE
TypeError: Object orderNumber has no method 'rawCollection'

### ISSUE THREAD

**Issue by mwarren2** [Konecty/meteor-mongo-counter#4]
Here's my server code:

```
Meteor.methods({
    //uses meteor mongo-counter to get an atomic number
    getNextOrderNumber: function() {
        return incrementCounter('orderNumber');
    }
});
```

which throws this exception:

I20150414-17:22:41.490(2)? Exception while invoking method 'getNextOrderNumber' TypeError: Object orderNumber has no method 'rawCollection'
I20150414-17:22:41.491(2)?     at getCounterCollection (packages/konecty:mongo-counter/counter.coffee:2:14)
I20150414-17:22:41.491(2)?     at callCounter (packages/konecty:mongo-counter/counter.coffee:6:14)
I20150414-17:22:41.491(2)?     at _incrementCounter (packages/konecty:mongo-counter/counter.coffee:20:12)
I20150414-17:22:41.491(2)?     at [object Object].Meteor.methods.getNextOrderNumber (app/server/methods.js:16:16)
I20150414-17:22:41.491(2)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150414-17:22:41.491(2)?     at packages/ddp/livedata_server.js:648:1
I20150414-17:22:41.491(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150414-17:22:41.491(2)?     at packages/ddp/livedata_server.js:647:1
I20150414-17:22:41.491(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150414-17:22:41.492(2)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150414-17:22:41.492(2)?     at packages/ddp/livedata_server.js:546:1

**Comment by oskareke** [comment]
How did you resolve this?

**Comment by mwarren2** [comment]
To solve this I rolled my own solution:

```
getNextSequence: function(){
    var args = {
        query: {name: 'orderNumber'},
        upsert: true,
        update: {$inc: {seq: 1}},
        'new': true
    };
    //needs fongandrew:find-and-modify. Meteor may include findAndModify in the core in the future
    var counterObj = Counters.findAndModify(args);
    return counterObj.seq;
},
```
