### ISSUE TITLE
incrementCounter returns undefined after upgrading Meteor

### ISSUE THREAD

**Issue by tab00** [Konecty/meteor-mongo-counter#7]
It looks like upgrading Meteor to version 1.4 broke this package.

I created a new test app with just the following code added, and it prints `undefined` 10 times

```
Meteor.startup(() => {
    Counters = new Mongo.Collection('counters');

    for(i=0;i<10;i++)
        console.log(incrementCounter(Counters, "index"))
});
```

**Comment by tab00** [comment]
I managed to get the value simply by calling `Counters.findOne("index").next_val`. Though it would be better to have a proper solution.

**Comment by sampaiodiego** [comment]
fixed by https://github.com/Konecty/meteor-mongo-counter/commit/cca56926365e634e4cac0894685bcf7832054efe

you can run `meteor update konecty:mongo-counter` @tab00
